from .inflections import *
from .inflections_latin import *
from .names import *
from .names_patterns import *
from .text import *
from .tokens import *
from .ExtendedDoc import *
from .FindEntityInstances import *
from .ResolveEntityInstances import *